name: Deploy Hexo Site

on:
  push:
    branches:
      - main # 精准锁定你截图中的 main 分支

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        # 严格告诉服务器，进入你截图中的 one-blog 文件夹执行
        working-directory: ./one-blog
        run: |
          npm install --legacy-peer-deps

      - name: Build Hexo
        # 严格告诉服务器，进入你截图中的 one-blog 文件夹执行
        working-directory: ./one-blog
        run: |
          npx hexo clean
          npx hexo generate

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # 严格指向 one-blog 生成的静态网页包
          path: './one-blog/public'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
